## Exercise 0.0 :

---------------------------------------------------------------------------------

- Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
- Create a random tensor with shape (7, 7).
- Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
- Set the random seed to 0 and do exercises 2 & 3 over again.
- Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
- Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this)
- Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
- Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
- Find the maximum and minimum values of the output of 7.
- Find the maximum and minimum index values of the output of 7.
- Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [10]:
import torch
import numpy as np

In [11]:
# Create a random tensor with shape (7, 7).
tens1 = torch.rand(7, 7)
tens1

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

In [12]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
tens2 = torch.rand(1, 7)
product = torch.mm(tens1, tens2.T)
product

tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])

In [13]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
tens1 = torch.rand(7, 7)
tens2 = torch.rand(1, 7)
product = torch.mm(tens1, tens2.T)
product

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [14]:
# set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [15]:
# Create two random tensors of shape (2, 3) and send them both to the GPU
torch.manual_seed(1234)
tens3 = torch.rand(2, 3)
tens4 = torch.rand(2, 3)
# tens3 = tens3.cuda()
# tens4 = tens4.cuda()
tens3, tens4

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [16]:
# Perform a matrix multiplication on the tensors you created in 6
prod2 = torch.mm(tens3, tens4.T)
prod2, prod2.dtype

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.float32)

In [17]:
# Find the maximum and minimum values of the output of 7.
max = torch.max(prod2)
print(f"THE MAXIMUM VALUE IS: {max}")
# print(max.dtype)
# Find the maximum and minimum index values of the output of 7.
min = torch.min(prod2)
print(f"THE MINIMUM VALUE IS: {min}")

THE MAXIMUM VALUE IS: 0.5617256760597229
THE MINIMUM VALUE IS: 0.3647301495075226


In [18]:
# Make a random tensor with shape (1, 1, 1, 10) and
# then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
tens5 = torch.rand(size=(1, 1, 1, 10))
squeezed_tens = np.squeeze(tens5)
print(f"THE SIZE OF THE TENSOR BEFORE SQUEEZING : {tens5.shape}")
print(f"THE SIZE OF THE TENSOR AFTER SQUEEZING : {squeezed_tens.shape}")

THE SIZE OF THE TENSOR BEFORE SQUEEZING : torch.Size([1, 1, 1, 10])
THE SIZE OF THE TENSOR AFTER SQUEEZING : torch.Size([10])
